### ISSUE TITLE
Angular - Support affected template change

### ISSUE THREAD

**Issue by talgershman** [lemonade-hq/traf#15]
Hi,

In Angular a component can be sperated into .ts and .html ( AKA template file ), I noticed that if I only make a change to the template file it doesn't pick up any affected libs.

**Comment by EladBezalel** [comment]
Hey, thanks for submitting the issue,

You're right, since the html files aren't included in the lib tsconfig, traf currently ignore them.

There's a [getReferencingSourceFiles](https://ts-morph.com/details/source-files#getting-referencing-files) funciton in ts-morph, we might be able to include all non-ts/js files and look for referencing source files.

I'll look into it

**Comment by talgershman** [comment]
another option is to mark the component as 'dirty'.
if you find that the template file is changed then you can search for the file name -> 
usually it will be found in :
@Component({
  ...
  templateUrl: './my-temp.component.html',
...
})
then you can mark that component class as changed.

**Comment by EladBezalel** [comment]
I don't want to write code specifially for Angular, should be a generic solution

**Comment by EladBezalel** [comment]
fixed by #22
